export const RECEIVE_ADDRESS = 'receive_address'
export const RECEIVE_FOODTYPES = 'receive_foodtypes'
export const RECEIVE_SHOPLIST = 'receive_shoplist'
export const RECEIVE_USERINFO = 'receive_userinfo'
export const RESET_USERINFO = 'reset_userinfo'
export const RECEIVE_GOODS = 'receive_goods'
export const RECEIVE_RATINGS = 'receive_ratings'
export const RECEIVE_INFO = 'receive_info'
